stages:
  - build
  - notify

.tags_shell: &tags_shell
  tags:
    - azure-gr
    - shell
    
.tags_docker: &tags_docker
  tags:
    - rpp-dev-po01-ext
    - docker

.build_cmd: &build_cmd
  stage: build
  script:
    - echo $PWD
    - ls $CI_PROJECT_DIR
    - cd $CI_PROJECT_DIR
    - /usr/bin/docker build -f .docker/Dockerfile -t poace.azurecr.io/po/po-design-system .
    - /usr/bin/docker push poace.azurecr.io/po/po-design-system

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  <<: *tags_shell
  <<: *build_cmd
  only:
    - master
    - release/*
    - deploy


notify:
  stage: notify
  <<: *tags_docker
  only:
    - master
    - release/*
    - deploy
  image: poace.azurecr.io/po/devops/kube-helm:latest
  script:
    - kubectl rollout restart deploy -n po po-design-system
